name: Lint

on:
  push:
    branches:
      - "!main"
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: prune
        run: make prune
